# Generated by Django 5.2.17 on 2026-10-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_prestamo'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
    ]
