# Generated by Django 5.2.17 on 2026-09-30 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traslados', '0001_initial'),
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtraslado',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='ubicacion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrantes', to='ubicaciones.ubicacion'),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='ubicacion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salientes', to='ubicaciones.ubicacion'),
        ),
    ]
