# Generated by Django 5.2.17 on 2026-10-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudtraslado',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Solicitud de traslado', 'verbose_name_plural': 'Solicitudes de traslado'},
        ),
    ]
