# Generated by Django 5.2.17 on 2026-10-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
