# Generated by Django 5.2.17 on 2026-10-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='origen',
            field=models.CharField(blank=True, choices=[('COMPRADO', 'Comprado'), ('DONADO', 'Donado')], help_text='Cómo ingresó el activo a la facultad (opcional).', max_length=20),
        ),
    ]
