# Generated by Django 5.2.17 on 2026-10-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_origen_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='activo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activo',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie del fabricante, si lo tiene.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='ref',
            field=models.CharField(blank=True, help_text='Número REF (correlativo interno), si el activo lo tiene.', max_length=50, null=True, unique=True),
        ),
    ]
